bucket_list = ["Japan", "India", "Taiwan", "Brazil", "Korea"]
print(bucket_list)
print(sorted(bucket_list))
print(bucket_list)
print(sorted(bucket_list, reverse = True))
print(bucket_list)
bucket_list.reverse()
print(bucket_list)
bucket_list.reverse()
print(bucket_list)
bucket_list.sort()
print(bucket_list)
bucket_list.sort(reverse = True)
print(bucket_list)
